### ISSUE TITLE
Error in compiling slistartup.cc

### ISSUE THREAD

**Issue by graipher** [nest/nest-simulator#567]
When trying to compile on Ubuntu 16.10, with `./configure --prefix=/usr/local/`, I get the following error:

```
$ make
...
Making all in sli
make[1]: Entering directory '/home/USER/nest-2.10.0/sli'
depbase=`echo slistartup.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../libnestutil  -I../libnestutil -I../librandom -I../nestkernel -DPKGDATADIR=\"/usr/local/share/nest\" -DPKGDOCDIR=\"/usr/local/share/doc/nest\" -DPKGSOURCEDIR=\"/home/USER/nest-2.10.0\"  -W -Wall -pedantic -Wno-long-long  -O2  -fopenmp  -MT slistartup.lo -MD -MP -MF $depbase.Tpo -c -o slistartup.lo slistartup.cc &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../libnestutil -I../libnestutil -I../librandom -I../nestkernel -DPKGDATADIR=\"/usr/local/share/nest\" -DPKGDOCDIR=\"/usr/local/share/doc/nest\" -DPKGSOURCEDIR=\"/home/USER/nest-2.10.0\" -W -Wall -pedantic -Wno-long-long -O2 -fopenmp -MT slistartup.lo -MD -MP -MF .deps/slistartup.Tpo -c slistartup.cc  -fPIC -DPIC -o .libs/slistartup.o
slistartup.cc: In member function 'bool SLIStartup::checkpath(const string&, std::__cxx11::string&) const':
slistartup.cc:75:15: error: cannot convert 'std::ifstream {aka std::basic_ifstream<char>}' to 'bool' in return
   return ( in );
               ^
Makefile:709: recipe for target 'slistartup.lo' failed
make[1]: *** [slistartup.lo] Error 1
make[1]: Leaving directory '/home/USER/nest-2.10.0/sli'
Makefile:539: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by heplesser** [comment]
This is a duplicate of #220, which has been fixed by #389.
