### ISSUE TITLE
nest fails to build with Python 3.11: error: cannot convert 'PyObject*' {aka '_object*'} to 'PyTracebackObject*' {aka '_traceback*'} in assignmen

### ISSUE THREAD

**Issue by sanjayankur31** [nest/nest-simulator#2390]
**Describe the bug**
nest fails to build with Python 3.11.0a6.

```
/builddir/build/BUILD/nest-simulator-3.2/nest-simulator-3.2/pynest/pynestkernel.cxx: In function 'PyObject* __Pyx_Coroutine_SendEx(__pyx_CoroutineObject*, PyObject*, int)':
/builddir/build/BUILD/nest-simulator-3.2/nest-simulator-3.2/pynest/pynestkernel.cxx:36535:42: error: cannot convert 'PyObject*' {aka '_object*'} to 'PyTracebackObject*' {aka '_traceback*'} in assignment
36535 |         tb = __Pyx__ExceptionGetTraceback(exc_state->exc_value);
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
      |                                          |
      |                                          PyObject* {aka _object*}
make[2]: *** [pynest/CMakeFiles/pynestkernel.dir/build.make:84: pynest/CMakeFiles/pynestkernel.dir/pynestkernel.cxx.o] Error 1
```

The interpreter state’s representation of handled exceptions (a.k.a exc_info, or _PyErr_StackItem) now has only the exc_value field, exc_type and exc_traceback have been removed as their values can be derived from exc_value. (Contributed by Irit Katriel in bpo-45711.)

https://bugs.python.org/issue45711
https://docs.python.org/3.11/whatsnew/3.11.html

**Desktop/Environment (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu-18.04]: Fedora rawhide (37)
 - Python-Version: [e.g. Python 3.6]: Python 3.11.0a6
 - NEST-Version: [e.g. nest-2.18, or git hash]: 3.2
 - Installation: [e.g. conda packet, apt, with/out MPI, ...]: from source

**Additional context**
Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=2069657

**Comment by heplesser** [comment]
@sanjayankur31 Does the problem still persist with NEST 3.3 or current Github version?

**Comment by sanjayankur31** [comment]
I haven't had a chance to update the Fedora package to 3.3 yet. I'll test that out and get back to you.

**Comment by terhorstd** [comment]
May be related to #2497

**Comment by heplesser** [comment]
@sanjayankur31 Any updates? I have been able to build and test NEST 3.4rc1 with Python 3.11 (from Homebrew) on macOS 13.1 on a machine with Apple Silicon.

**Comment by sanjayankur31** [comment]
I just checked our builds, and 3.3 builds OK with 3.11 and 3.12, So I think this has been fixed. Closing.

https://koji.fedoraproject.org/koji/packageinfo?packageID=27405
