### ISSUE TITLE
pynestkernel not compiling on OSX

### ISSUE THREAD

**Issue by rgerkin** [nest/nest-simulator#65]
I'm having trouble getting a compiled pynestkernel library on OSX.  Standard installation doesn't even attempt to compile it and put it in the build directory, so I get: 

`File "/Users/rgerkin/Desktop/nest-2.6.0/pynest/nest/__init__.py", line 52, in <module>`
`from . import pynestkernel as _kernel`
`ImportError: cannot import name 'pynestkernel'`

due to the file being missing.  The installation script isn't even trying to compile it to a shared library (.so)

If I try to cythonize it myself, I can get a .cpp, but I can never get it to compile, although perhaps there is magic set of flags that will work.  

Does anyone have a reproducible recipe for installation in OSX 10.9?

**Comment by tammoippen** [comment]
Hello rgerkin,

Here you can find general instructions, on how to build NEST on OSX: http://www.nest-simulator.org/installation-2/ (you have to scroll down a bit).

Further, I wrote up a Xcode workflow for OSX 10.10, but I am sure it will also work with OSX 10.9. You can find it here: https://nest.github.io/nest-simulator/xcode_workflow

I hope this helps for the pynestkernel issue. Please let me know.

Best,
Tammo
