### ISSUE TITLE
GetDefaults occasionally causes bad_alloc if NEST is built with MUSIC

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1449]
We have in recent weeks seen a number of Travis build failures in stage 7 (the "all in build"), e.g.

- https://travis-ci.org/nest/nest-simulator/jobs/655816865?utm_medium=notification&utm_source=github_status
- https://travis-ci.org/nest/nest-simulator/jobs/655980035?utm_medium=notification&utm_source=github_status

The failure can occur in different tests, but common is that

- a `bad_alloc` exception is triggered
- `GetDefaults` is involved.

Since this issue obstructs testing, I escalate it to critical.

Experimenting on Travis, I have confirmed that the issue occurs if NEST is built with just MPI and MUSIC, but no threading, GSL, LDTL, Python, Readline.

I have also confirmed the issue under OSX building with gcc 9.2.0. There
```
for i in {1..20}; do nest --verbosity=ERROR -c "modeldict keys { ResetKernel GetDefaults ; } forall" ; done
```
will usually evoke in one of the twenty runs
```
Mar 01 17:23:21 GetDefaults_l [Error]: C++Exception
    cannot create std::vector larger than max_size()
```
In all cases I have observed, the last model for which `GetDefaults` was called, was `music_rate_in_proxy`, although a test which only called `GetDefaults` on that model did not trigger the exception  in 200 runs.

The following version calls `GetDefaults` only on the `music_` models and prints the model names. It usually triggers an exception at least once in twenty runs.
```
for i in {1..20}; do 
    nest --verbosity=ERROR -c "modeldict keys { dup cvs 6 Take (music_) eq 
           { ResetKernel dup =only ( ) =only GetDefaults ; } 
           { ; } ifelse 
       } forall ( ) = ";
done
```

**Comment by hakonsbm** [comment]
@heplesser I cannot seem to reproduce the error using GCC with `-O0`. When using `-O3` the compiler complains about an undefined reference. By adding 
```C++
#include "event_delivery_manager_impl.h"
```
in music_rate_in_proxy.cpp it compiles but is also unable to reproduce the error.

CMake with `-O0` or `-O3` complains about additional undefined references when linking:
```
../models/libmodels.so: undefined reference to `MUSIC::Setup::publishContOutput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)'
../models/libmodels.so: undefined reference to `MUSIC::Setup::publishEventOutput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)'
../nestkernel/libnestkernel.so: undefined reference to `MUSIC::Setup::publishEventInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)'
../models/libmodels.so: undefined reference to `MUSIC::Setup::publishContInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)'
../models/libmodels.so: undefined reference to `MUSIC::Setup::publishMessageInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by heplesser** [comment]
@hakonsbm Thanks for investigating. Using
- macOS 10.14.6
- gcc 9.2.0 (homebrew) or Apple's clang 10.0.1
- Music 1.1.16
- OpenMPI 4.0.2 (locally built with C++ bindings)

I find the following
- Compiling with gcc
    - the bad_alloc occurs with -O0 and -O2
    - adding `#include "event_delivery_manager_impl.h` makes no difference, bad_alloc still occurs
- Compiling with clang 
    - a number of warnings originating from Music headers
    - the following linker error (similar to what you obeserved) when linking libnestkernel:
```
Undefined symbols for architecture x86_64:
  "MUSIC::Setup::publishContInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      nest::MusicRateInHandler::publish_port() in music_rate_in_handler.cpp.o
  "MUSIC::Setup::publishEventInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      nest::MusicEventHandler::publish_port() in music_event_handler.cpp.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by heplesser** [comment]
@hakonsbm Found it. The problem is at https://github.com/nest/nest-simulator/blob/a368a86e0a79aa9f72e5a59791deec2a3917b6e3/models/music_rate_in_proxy.cpp#L152:
```c++
void
nest::music_rate_in_proxy::get_status( DictionaryDatum& d ) const
{
  P_.get( d );
  S_.get( d );

  ( *d )[ names::data ] = DoubleVectorDatum( new std::vector< double >( B_.data_ ) );
}
```
The problem is that `B_.data_` is a `double`... . 

@jakobj Any memory of why this tries to return a single double as a vector?

**Comment by hakonsbm** [comment]
I can't find any other potential places where this is a problem, so hopefully this is the only place. In music_cont_in_proxy.cpp there is a similar `get_status()` function, but there `B_.data_` is a `vector` of `double`s. It should presumably be the same in music_rate_in_proxy.

Additionally, music_rate_in_proxy doesn't seem to attempt to fill `B_.data_` with anything. If it had, the problem of `B_.data_` being a `double` and not a `vector` of `double`s could have been discovered at compile time.

**Comment by heplesser** [comment]
@jakobj @weidel-p Could you take a look again at the Music rate proxies you introduced with #1245.?
- After quite a bit of code-reading, it is still a mystery to me how any data is ever place in `B_.data_`.
- Is it correct that `B_.data_` is a plain `double` member variable?

**Comment by jakobj** [comment]
@heplesser @hakonsbm unfortunately I really don't remember. will stare at the code until I do and report back. It's possible that it's actually never used, since the communication logic might be handled by `MusicRateInHandler`.

**Comment by jakobj** [comment]
update: it looks like the rate proxies are not the only thing that's broken. simulations with event proxies seem to hang. looking for the commit that leads to this strange behaviour.

**Comment by jakobj** [comment]
if i didn't loose too much concentration during the bisect, 8f3890b44b should be the first one to make NEST get stuck when MUSIC devices are present. will have another look tomorrow, but I'm already tagging @jougs here ;)

**Comment by heplesser** [comment]
@jakobj @hakonsbm It seems we have two issues here: The Incorrect `vector` initialization in `music_rate_in_proxy` which leads to occasional failures in our test suite, and something more complex that causes simulations with MUSIC to hang under certain circumstances.

@hakonsbm Since the first problem blocks all our unit testing, I would suggest to fix this with a minimal fix, just initializing the `vector` correctly.

@jakobj Could you create a separate issue for the problem that NEST can get stuck?

**Comment by hakonsbm** [comment]
@heplesser I have created #1458.
